admin_usergroup:
    path:     /
    defaults: { _controller: "CDNServerCore:Admin/UserGroup:index" }

admin_usergroup_show:
    path:     /{id}/show
    defaults: { _controller: "CDNServerCore:Admin/UserGroup:show" }

admin_usergroup_new:
    path:     /new
    defaults: { _controller: "CDNServerCore:Admin/UserGroup:new" }

admin_usergroup_create:
    path:     /create
    defaults: { _controller: "CDNServerCore:Admin/UserGroup:create" }
    requirements: { _method: post }

admin_usergroup_edit:
    path:     /{id}/edit
    defaults: { _controller: "CDNServerCore:Admin/UserGroup:edit" }

admin_usergroup_update:
    path:     /{id}/update
    defaults: { _controller: "CDNServerCore:Admin/UserGroup:update" }
    requirements: { _method: post|put }

admin_usergroup_delete:
    path:     /{id}/delete
    defaults: { _controller: "CDNServerCore:Admin/UserGroup:delete" }
    requirements: { _method: post|delete }
