security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       ROLE_MANAGER
        ROLE_MANAGER:     ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:  ^/api/
            security: false

        login:
            pattern:  ^/login$
            anonymous: true

        secured_area:
            pattern:    ^/
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_provider: form.csrf_provider
                default_target_path:  /
            logout:
                path:       /logout
                target:     /
            anonymous: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
