api_resource_check:
    path:     /check
    defaults: { _controller: "CDNServerCore:Api/Resource:check" }
    requirements: { _method: get }

api_resource_fetch_sync:
    path:     /fetch
    defaults: { _controller: "CDNServerCore:Api/Resource:fetch" }
    requirements: { _method: post }
api_resource_fetch_async:
    path:     /a/fetch
    defaults: { _controller: "CDNServerCore:Api/Resource:fetchAsync" }
    requirements: { _method: post }

api_resource_push_sync:
    path:     /push
    defaults: { _controller: "CDNServerCore:Api/Resource:push" }
    requirements: { _method: post }
api_resource_push_async:
    path:     /a/push
    defaults: { _controller: "CDNServerCore:Api/Resource:pushAsync" }
    requirements: { _method: post }
