
##
# Admin
##

admin_hub:
    pattern:  /
    defaults: { _controller: CDNServerCoreBundle:Admin\Hub:hub }

CDNServerCoreBundle_Admin_Project:
    resource: "@CDNServerCoreBundle/Resources/config/routing/admin/project_routing.yml"
    prefix:   /project

CDNServerCoreBundle_Admin_User:
    resource: "@CDNServerCoreBundle/Resources/config/routing/admin/user_routing.yml"
    prefix:   /user

CDNServerCoreBundle_Admin_UserGroup:
    resource: "@CDNServerCoreBundle/Resources/config/routing/admin/usergroup_routing.yml"
    prefix:   /user-group

##
# API
##

CDNServerCoreBundle_Api_Resource:
    resource: "@CDNServerCoreBundle/Resources/config/routing/api/resource_routing.yml"
    prefix:   /api/resource

##
# FOS User Bundle
##

CDNServerCoreBundle_FOSUser:
  resource: "@CDNServerCoreBundle/Resources/config/routing/fosuser_routing.yml"
  prefix: /
