#fos_user_security_login            /login
#fos_user_security_check            /login_check
#fos_user_security_logout           /logout
CDNServerCore_FOSUser_Security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile_show              /
#fos_user_profile_edit              /edit
CDNServerCore_FOSUser_Profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile/sub

#fos_user_registration_register     /
#fos_user_registration_check_email  /check-email
#fos_user_registration_confirm      /confirm/{token}
#fos_user_registration_confirmed    /confirmed
CDNServerCore_FOSUser_Register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

#fos_user_resetting_request         /request
#fos_user_resetting_send_email      /send-email
#fos_user_resetting_check_email     /check-email
#fos_user_resetting_reset           /reset/{token}
CDNServerCore_FOSUser_Resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

#fos_user_change_password           /change-password
CDNServerCore_FOSUser_Password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
