# These service parameters can be splitted into several specialized files
# If you do, put them into the 'config/services/parameters' directory and
# maybe try to use the same naming conventions as in declaration files.
# ie :
#   declarations :  config/services/declarations/api.yml  
#   parameters :    config/services/parameters/api.yml

parameters:

  resource_root_dir:  "/var/www/cdn/"
  resource_ext_path:  "http://placeholder.com/cdn/"
