imports:
  - { resource: services/service_parameters.yml }

#locally overloaded parameters
parameters:  
  resource_root_dir:  "/var/www/cdn-rec/"
  resource_ext_path:  "http://cdn-orange.com/cdn-rec/"
