services:
  resource.writer:
    class:        CDNServer\Core\Write\ResourceWriter
    arguments:
      - %resource_ext_path%
      - %resource_root_dir%
      - @doctrine.orm.entity_manager

  resource.fetcher:
    class:        CDNServer\Core\Fetch\ResourceFetcher
    arguments:
      - @resource.writer
      - @doctrine.orm.entity_manager

  resource.factory.simple:
    class:        CDNServer\Core\Factory\ResourceFactory
    arguments:
      - @resource.writer
      - @doctrine.orm.entity_manager
  resource.factory.url:
    class:        CDNServer\Core\Factory\UrlResourceFactory
    arguments:
      - @resource.writer
      - @doctrine.orm.entity_manager
  resource.factory.stream:
    class:        CDNServer\Core\Factory\StreamResourceFactory
    arguments:
      - @resource.writer
      - @doctrine.orm.entity_manager
