services:
  view.global.listener:
    class:        CDNServer\CoreBundle\EventListener\ViewListener
    arguments:
      - @templating
      - 'twig'
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

  async.fetch.listener:
    class:        CDNServer\CoreBundle\EventListener\AsyncFetchListener
    arguments:
      - @service_container
      - @doctrine.orm.entity_manager
      - @logger
    tags:
      - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
